from io import BytesIO
from zipfile import ZipFile

import pytest
from docx import Document

from app.services.document_generator import generate_docx_bytes


def _read_docx(content: bytes) -> Document:
    return Document(BytesIO(content))


def _docx_part(content: bytes, name: str) -> str:
    with ZipFile(BytesIO(content)) as archive:
        return archive.read(name).decode("utf-8")


def test_generate_docx_renders_headings_lists_and_text():
    content = """# Recommendation

Use the low-overhead option.

## Next steps
- Configure the database
- Run migrations
1. Smoke test production
2. Watch costs
"""
    doc = _read_docx(generate_docx_bytes("Deployment plan", content, "Generated by Fronei"))

    text = "\n".join(p.text for p in doc.paragraphs)
    assert "Deployment plan" in text
    assert "Generated by Fronei" in text
    assert "Recommendation" in text
    assert "Use the low-overhead option." in text
    assert "Configure the database" in text
    assert "Smoke test production" in text


def test_generate_docx_renders_markdown_table():
    content = """| Option | Cost | Notes |
| --- | --- | --- |
| Railway | Low | Lowest overhead |
| VPS | Lower | More maintenance |
"""
    doc = _read_docx(generate_docx_bytes("Hosting comparison", content))

    assert len(doc.tables) == 1
    table = doc.tables[0]
    assert table.cell(0, 0).text == "Option"
    assert table.cell(1, 0).text == "Railway"
    assert table.cell(2, 2).text == "More maintenance"


def test_generate_docx_preserves_common_inline_formatting():
    content = "Keep **bold text**, *italic text*, `code text`, and [Fronei](https://example.com)."
    doc = _read_docx(generate_docx_bytes("Inline formatting", content))

    paragraph = next(p for p in doc.paragraphs if "Keep " in p.text)
    runs_by_text = {run.text: run for run in paragraph.runs if run.text}
    assert runs_by_text["bold text"].bold
    assert runs_by_text["italic text"].italic
    assert runs_by_text["code text"].font.name == "Courier New"
    assert "w:hyperlink" in paragraph._p.xml
    assert any(rel.target_ref == "https://example.com" for rel in paragraph.part.rels.values())


def test_generate_docx_preserves_inline_formatting_in_lists_and_tables():
    content = """- **Pinned** memory

| Field | Value |
| --- | --- |
| Style | *Concise* |
"""
    doc = _read_docx(generate_docx_bytes("Inline containers", content))

    list_paragraph = next(p for p in doc.paragraphs if "Pinned" in p.text)
    assert any(run.text == "Pinned" and run.bold for run in list_paragraph.runs)
    table_cell = doc.tables[0].cell(1, 1).paragraphs[0]
    assert any(run.text == "Concise" and run.italic for run in table_cell.runs)


@pytest.mark.parametrize(
    ("doc_type", "has_cover", "has_toc"),
    [
        ("executive_report", True, True),
        ("proposal", True, True),
        ("technical_spec", True, False),
        ("memo", False, False),
        ("meeting_notes", False, False),
        ("one_pager", False, False),
        ("letter", False, False),
    ],
)
def test_generate_docx_type_layouts(doc_type: str, has_cover: bool, has_toc: bool):
    content = generate_docx_bytes(
        "Client Readiness Plan",
        "# Body\n\n## Section A\n\nThis is the document body.\n\n## Section B\n\nMore text.",
        "Generated by Fronei",
        doc_type=doc_type,
    )
    doc = _read_docx(content)
    text = "\n".join(p.text for p in doc.paragraphs)
    document_xml = _docx_part(content, "word/document.xml")
    footer_xml = _docx_part(content, "word/footer1.xml")

    assert "PAGE" in footer_xml
    assert "Fronei" in footer_xml
    assert ("w:type=\"page\"" in document_xml) is has_cover or (has_toc and "w:type=\"page\"" in document_xml)
    if has_cover:
        assert "Prepared for Fronei" in text
        assert "Generated by Fronei" in text
    if has_toc:
        assert "Table of Contents" in text
        assert text.count("Section A") >= 2
        assert text.count("Section B") >= 2
    # The TOC is a static heading list, never a Word TOC field — field codes
    # (w:fldChar/instrText) trigger a "fields may refer to other files"
    # prompt when Word opens the doc. The footer's PAGE field is the only
    # field code expected anywhere in the document.
    assert "instrText" not in document_xml
    assert "fldChar" not in document_xml
    # updateFields is intentionally NOT set, since it also triggers that prompt.
    assert "updateFields" not in _docx_part(content, "word/settings.xml")


def test_generate_docx_unknown_doc_type_preserves_legacy_layout():
    content = generate_docx_bytes(
        "Plain Export",
        "# Body\n\nText.",
        "Generated by Fronei",
        doc_type="unknown",
    )
    document_xml = _docx_part(content, "word/document.xml")

    assert "Prepared for Fronei" not in "\n".join(p.text for p in _read_docx(content).paragraphs)
    assert "footerReference" not in document_xml


def test_generate_docx_does_not_duplicate_title_with_cover():
    content = generate_docx_bytes(
        "Q3 Hardening Report",
        "# Q3 Hardening Report\n\n## Executive Summary\nSome text.\n",
        "Generated by Fronei",
        doc_type="executive_report",
    )
    doc = _read_docx(content)
    heading_1s = [p.text for p in doc.paragraphs if p.style.name == "Heading 1" and p.text.strip()]

    assert "Q3 Hardening Report" not in heading_1s
    assert heading_1s == ["Table of Contents"]


def test_generate_docx_does_not_duplicate_title_with_compact_header():
    content = generate_docx_bytes(
        "Status Memo",
        "# Status Memo\n\nBody text.\n",
        "Generated by Fronei",
        doc_type="memo",
    )
    doc = _read_docx(content)
    heading_1s = [p.text for p in doc.paragraphs if p.style.name == "Heading 1" and p.text.strip()]

    assert heading_1s == ["Status Memo"]
    body_paragraphs = [p.text for p in doc.paragraphs if p.text.strip()]
    assert body_paragraphs.count("Status Memo") == 1
