import json
from io import BytesIO
from zipfile import ZipFile

import pytest
from docx import Document
from pptx import Presentation

from app.services.document_generator import (
    _pptx_layout_for_role,
    deck_plan_to_markdown,
    generate_docx_bytes,
    generate_pptx_bytes,
    generate_xlsx_bytes,
    parse_deck_plan,
    repair_deck_plan_for_qa,
)


def _read_docx(content: bytes) -> Document:
    return Document(BytesIO(content))


def _docx_part(content: bytes, name: str) -> str:
    with ZipFile(BytesIO(content)) as archive:
        return archive.read(name).decode("utf-8")


def _slide_texts(slide) -> list:
    """All text found in a slide's shapes (title placeholders, text boxes, etc.).

    Works for both python-pptx-rendered slides (which use title placeholders)
    and PptxGenJS-rendered slides (which use plain text boxes only).
    """
    texts = []
    for shape in slide.shapes:
        if hasattr(shape, "text") and shape.text:
            texts.append(shape.text)
    return texts


def _all_decks_text(deck) -> list:
    texts = []
    for slide in deck.slides:
        texts.extend(_slide_texts(slide))
    return texts


def test_generate_docx_renders_headings_lists_and_text():
    content = """# Recommendation

Use the low-overhead option.

## Next steps
- Configure the database
- Run migrations
1. Smoke test production
2. Watch costs
"""
    doc = _read_docx(generate_docx_bytes("Deployment plan", content, "Generated by Fronei"))

    text = "\n".join(p.text for p in doc.paragraphs)
    assert "Deployment plan" in text
    assert "Generated by Fronei" in text
    assert "Recommendation" in text
    assert "Use the low-overhead option." in text
    assert "Configure the database" in text
    assert "Smoke test production" in text


def test_generate_docx_renders_markdown_table():
    content = """| Option | Cost | Notes |
| --- | --- | --- |
| Railway | Low | Lowest overhead |
| VPS | Lower | More maintenance |
"""
    doc = _read_docx(generate_docx_bytes("Hosting comparison", content))

    assert len(doc.tables) == 1
    table = doc.tables[0]
    assert table.cell(0, 0).text == "Option"
    assert table.cell(1, 0).text == "Railway"
    assert table.cell(2, 2).text == "More maintenance"


def test_generate_docx_preserves_common_inline_formatting():
    content = "Keep **bold text**, *italic text*, `code text`, and [Fronei](https://example.com)."
    doc = _read_docx(generate_docx_bytes("Inline formatting", content))

    paragraph = next(p for p in doc.paragraphs if "Keep " in p.text)
    runs_by_text = {run.text: run for run in paragraph.runs if run.text}
    assert runs_by_text["bold text"].bold
    assert runs_by_text["italic text"].italic
    assert runs_by_text["code text"].font.name == "Courier New"
    assert "w:hyperlink" in paragraph._p.xml
    assert any(rel.target_ref == "https://example.com" for rel in paragraph.part.rels.values())


def test_generate_docx_handles_nested_inline_markdown_and_link_parentheses():
    content = "Use **bold with *nested italic*** and [source](https://example.com/path_(v2))."
    doc = _read_docx(generate_docx_bytes("Nested inline", content))

    paragraph = next(p for p in doc.paragraphs if "bold with" in p.text)
    runs_by_text = {run.text: run for run in paragraph.runs if run.text}

    assert runs_by_text["bold with "].bold
    assert runs_by_text["nested italic"].bold
    assert runs_by_text["nested italic"].italic
    assert "w:hyperlink" in paragraph._p.xml
    assert any(rel.target_ref == "https://example.com/path_(v2)" for rel in paragraph.part.rels.values())


def test_generate_docx_preserves_inline_formatting_in_lists_and_tables():
    content = """- **Pinned** memory

| Field | Value |
| --- | --- |
| Style | *Concise* |
"""
    doc = _read_docx(generate_docx_bytes("Inline containers", content))

    list_paragraph = next(p for p in doc.paragraphs if "Pinned" in p.text)
    assert any(run.text == "Pinned" and run.bold for run in list_paragraph.runs)
    table_cell = doc.tables[0].cell(1, 1).paragraphs[0]
    assert any(run.text == "Concise" and run.italic for run in table_cell.runs)


def test_generate_xlsx_cleans_nested_inline_markdown():
    workbook_bytes = generate_xlsx_bytes(
        "Financial model",
        "# Summary\n\n- **Margin with *sensitivity*** and [source](https://example.com/a_(b))",
    )
    from openpyxl import load_workbook

    wb = load_workbook(BytesIO(workbook_bytes))
    values = [cell.value for row in wb["Overview"].iter_rows() for cell in row if cell.value]

    assert "• Margin with sensitivity and source (https://example.com/a_(b))" in values


@pytest.mark.parametrize(
    ("doc_type", "has_cover", "has_toc"),
    [
        ("executive_report", True, True),
        ("proposal", True, True),
        ("technical_spec", True, False),
        ("memo", False, False),
        ("meeting_notes", False, False),
        ("one_pager", False, False),
        ("letter", False, False),
    ],
)
def test_generate_docx_type_layouts(doc_type: str, has_cover: bool, has_toc: bool):
    content = generate_docx_bytes(
        "Client Readiness Plan",
        "# Body\n\n## Section A\n\nThis is the document body.\n\n## Section B\n\nMore text.",
        "Generated by Fronei",
        doc_type=doc_type,
    )
    doc = _read_docx(content)
    text = "\n".join(p.text for p in doc.paragraphs)
    document_xml = _docx_part(content, "word/document.xml")
    footer_xml = _docx_part(content, "word/footer1.xml")

    assert "PAGE" in footer_xml
    assert "Fronei" in footer_xml
    assert ("w:type=\"page\"" in document_xml) is has_cover or (has_toc and "w:type=\"page\"" in document_xml)
    if has_cover:
        assert "Prepared for Fronei" in text
        assert "Generated by Fronei" in text
    if has_toc:
        assert "Table of Contents" in text
        assert text.count("Section A") >= 2
        assert text.count("Section B") >= 2
    # The TOC is a static heading list, never a Word TOC field — field codes
    # (w:fldChar/instrText) trigger a "fields may refer to other files"
    # prompt when Word opens the doc. The footer's PAGE field is the only
    # field code expected anywhere in the document.
    assert "instrText" not in document_xml
    assert "fldChar" not in document_xml
    # updateFields is intentionally NOT set, since it also triggers that prompt.
    assert "updateFields" not in _docx_part(content, "word/settings.xml")


def test_generate_docx_unknown_doc_type_preserves_legacy_layout():
    content = generate_docx_bytes(
        "Plain Export",
        "# Body\n\nText.",
        "Generated by Fronei",
        doc_type="unknown",
    )
    document_xml = _docx_part(content, "word/document.xml")

    assert "Prepared for Fronei" not in "\n".join(p.text for p in _read_docx(content).paragraphs)
    assert "footerReference" not in document_xml


def test_generate_docx_does_not_duplicate_title_with_cover():
    content = generate_docx_bytes(
        "Q3 Hardening Report",
        "# Q3 Hardening Report\n\n## Executive Summary\nSome text.\n",
        "Generated by Fronei",
        doc_type="executive_report",
    )
    doc = _read_docx(content)
    heading_1s = [p.text for p in doc.paragraphs if p.style.name == "Heading 1" and p.text.strip()]

    assert "Q3 Hardening Report" not in heading_1s
    assert heading_1s == ["Table of Contents"]


def test_generate_docx_does_not_duplicate_title_with_compact_header():
    content = generate_docx_bytes(
        "Status Memo",
        "# Status Memo\n\nBody text.\n",
        "Generated by Fronei",
        doc_type="memo",
    )
    doc = _read_docx(content)
    heading_1s = [p.text for p in doc.paragraphs if p.style.name == "Heading 1" and p.text.strip()]

    assert heading_1s == ["Status Memo"]
    body_paragraphs = [p.text for p in doc.paragraphs if p.text.strip()]
    assert body_paragraphs.count("Status Memo") == 1


def test_generate_pptx_renders_slide_plan_and_speaker_notes():
    content = """# Client AI Strategy
*For: Executive steering committee*

## The decision is timing-sensitive
- Demand is already showing up in operations
- Platform choice affects cost and governance
Speaker notes: Emphasize that this is a sequencing decision, not just tooling.

## Options
| Option | Best fit |
| --- | --- |
| Build | Differentiated workflow |
| Buy | Speed to value |
"""
    deck = Presentation(BytesIO(generate_pptx_bytes("Client AI Strategy", content)))

    slide_texts = [_slide_texts(slide) for slide in deck.slides]
    assert "Client AI Strategy" in slide_texts[0]
    assert any("The decision is timing-sensitive" in texts for texts in slide_texts)
    assert any("Options" in texts for texts in slide_texts)
    assert any("Demand is already showing up" in shape.text for slide in deck.slides for shape in slide.shapes if hasattr(shape, "text"))
    table_text = []
    for slide in deck.slides:
        for shape in slide.shapes:
            if getattr(shape, "has_table", False):
                table = shape.table
                for row in table.rows:
                    table_text.extend(cell.text for cell in row.cells)
    assert "Build" in table_text
    notes_text = "\n".join(slide.notes_slide.notes_text_frame.text for slide in deck.slides)
    assert "sequencing decision" in notes_text


def test_generate_pptx_renders_structured_deck_plan_json():
    content = json.dumps({
        "title": "Client AI Strategy",
        "subtitle": "For the executive steering committee",
        "slides": [
            {"layout": "section", "title": "Decision context"},
            {
                "layout": "bullets",
                "title": "The decision is timing-sensitive",
                "bullets": [
                    "Operational demand is already visible",
                    "Platform choice affects governance",
                ],
                "speaker_notes": "Frame this as a sequencing choice, not a tool preference.",
            },
            {
                "layout": "comparison",
                "title": "Buy is faster; build is more defensible",
                "columns": [
                    {"heading": "Buy", "bullets": ["Fastest launch", "Less workflow control"]},
                    {"heading": "Build", "bullets": ["Differentiated workflow", "Higher delivery risk"]},
                ],
            },
            {
                "layout": "table",
                "title": "Options differ most on speed and control",
                "table": {
                    "headers": ["Option", "Best fit"],
                    "rows": [["Buy", "Speed"], ["Build", "Differentiation"]],
                },
            },
        ],
    })

    deck = Presentation(BytesIO(generate_pptx_bytes("Fallback title", content)))
    slide_texts = [_slide_texts(slide) for slide in deck.slides]

    assert "Client AI Strategy" in slide_texts[0]
    assert any("Decision context" in texts for texts in slide_texts)
    assert any("The decision is timing-sensitive" in texts for texts in slide_texts)
    assert any("Buy is faster; build is more defensible" in texts for texts in slide_texts)
    assert any("Fastest launch" in shape.text for slide in deck.slides for shape in slide.shapes if hasattr(shape, "text"))
    table_text = []
    for slide in deck.slides:
        for shape in slide.shapes:
            if getattr(shape, "has_table", False):
                table = shape.table
                for row in table.rows:
                    table_text.extend(cell.text for cell in row.cells)
    assert "Differentiation" in table_text
    notes_text = "\n".join(slide.notes_slide.notes_text_frame.text for slide in deck.slides)
    assert "sequencing choice" in notes_text


def test_generate_pptx_uses_builtin_template_without_sample_slides():
    content = json.dumps({
        "title": "Platform Modernization",
        "slides": [
            {
                "layout": "bullets",
                "title": "Phased migration lowers execution risk",
                "bullets": ["Start with low-coupling domains", "Retire legacy components deliberately"],
            },
        ],
    })

    deck = Presentation(BytesIO(generate_pptx_bytes(
        "Fallback title",
        content,
        template_id="data-product-os",
    )))

    def _slide_title(slide):
        if slide.shapes.title:
            return slide.shapes.title.text
        for shape in slide.shapes:
            if shape.has_text_frame and shape.text_frame.text.strip():
                return shape.text_frame.text.strip()
        return ""

    slide_titles = [_slide_title(slide) for slide in deck.slides]

    assert len(deck.slides) == 2
    assert slide_titles == ["Platform Modernization", "Phased migration lowers execution risk"]


def test_generate_pptx_renders_new_layout_hints():
    content = json.dumps({
        "title": "AI Platform Roadmap",
        "subtitle": "For the steering committee",
        "slides": [
            {
                "layout": "executive_summary",
                "title": "The platform pays for itself within a year",
                "bullets": [
                    "Consolidating onto one platform cuts run-rate cost by 30%",
                    "Reduces vendor sprawl across three business units",
                    "Unlocks shared data foundation for future AI use cases",
                ],
            },
            {
                "layout": "decision_slide",
                "title": "Proceed with a phased platform consolidation",
                "bullets": [
                    "Consolidate onto Platform A starting Q3",
                    "Lower long-term TCO than maintaining three platforms",
                    "Vendor has committed migration support",
                ],
            },
            {
                "layout": "roadmap",
                "title": "Three phases over twelve months",
                "phases": [
                    {"label": "Phase 1", "title": "Foundation", "description": "Stand up shared infrastructure"},
                    {"label": "Phase 2", "title": "Migration", "description": "Move priority workloads"},
                    {"label": "Phase 3", "title": "Optimization", "description": "Retire legacy platforms"},
                ],
            },
            {
                "layout": "architecture",
                "title": "Target architecture centralizes data access",
                "bullets": ["Single API gateway", "Shared data layer", "Unified identity provider"],
            },
            {
                "layout": "risk_matrix",
                "title": "Key migration risks are manageable",
                "table": {
                    "headers": ["Risk", "Likelihood", "Impact", "Owner"],
                    "rows": [["Data loss during cutover", "Low", "High", "Platform team"]],
                },
            },
            {
                "layout": "appendix",
                "title": "Supporting detail",
                "bullets": [f"Detail point {i}" for i in range(8)],
            },
        ],
    })

    deck = Presentation(BytesIO(generate_pptx_bytes("Fallback title", content)))
    slide_texts = [_slide_texts(slide) for slide in deck.slides]

    assert any("The platform pays for itself within a year" in texts for texts in slide_texts)
    assert any("Proceed with a phased platform consolidation" in texts for texts in slide_texts)
    assert any("Three phases over twelve months" in texts for texts in slide_texts)
    assert any("Target architecture centralizes data access" in texts for texts in slide_texts)
    assert any("Key migration risks are manageable" in texts for texts in slide_texts)
    assert any("Supporting detail" in texts for texts in slide_texts)

    all_text = []
    for slide in deck.slides:
        for shape in slide.shapes:
            if hasattr(shape, "text"):
                all_text.append(shape.text)
    joined = "\n".join(all_text)

    # Executive summary headline rendered
    assert "Consolidating onto one platform cuts run-rate cost by 30%" in joined
    # Recommendation callout rendered with prefix
    assert "Recommendation: Consolidate onto Platform A starting Q3" in joined
    # Timeline phases rendered
    assert "Foundation" in joined and "Migration" in joined and "Optimization" in joined
    # Architecture placeholder + bullets rendered
    assert "Architecture diagram" in joined
    assert "Single API gateway" in joined
    # Appendix dense bullets all rendered (up to MAX_APPENDIX_BULLETS = 10)
    for i in range(8):
        assert f"Detail point {i}" in joined

    table_text = []
    for slide in deck.slides:
        for shape in slide.shapes:
            if getattr(shape, "has_table", False):
                table = shape.table
                for row in table.rows:
                    table_text.extend(cell.text for cell in row.cells)
    assert "Data loss during cutover" in table_text


def test_generate_pptx_renders_native_chart_for_financial_model():
    content = json.dumps({
        "title": "AI Platform Roadmap",
        "slides": [
            {
                "layout": "financial_model",
                "title": "Revenue grows steadily after consolidation",
                "chart": {
                    "type": "line",
                    "categories": ["2024", "2025", "2026"],
                    "series": [{"name": "Revenue ($M)", "values": [1.2, 1.8, 2.6]}],
                },
            },
        ],
    })

    deck = Presentation(BytesIO(generate_pptx_bytes("Fallback title", content)))
    slide_texts = [_slide_texts(slide) for slide in deck.slides]
    assert any("Revenue grows steadily after consolidation" in texts for texts in slide_texts)

    chart_shapes = [shape for slide in deck.slides for shape in slide.shapes if shape.has_chart]
    assert len(chart_shapes) == 1
    chart = chart_shapes[0].chart
    plot = chart.plots[0]
    assert list(plot.categories) == ["2024", "2025", "2026"]
    series = list(chart.series)
    assert series[0].name == "Revenue ($M)"
    assert list(series[0].values) == [1.2, 1.8, 2.6]


def test_generate_xlsx_adds_native_chart_for_numeric_table():
    content = (
        "# Revenue plan\n\n"
        "## Projection\n\n"
        "| Year | Revenue | Cost |\n"
        "| --- | --- | --- |\n"
        "| 2024 | 1.2 | 0.9 |\n"
        "| 2025 | 1.8 | 1.1 |\n"
        "| 2026 | 2.6 | 1.4 |\n"
    )
    workbook_bytes = generate_xlsx_bytes("Revenue plan", content)
    from openpyxl import load_workbook

    wb = load_workbook(BytesIO(workbook_bytes))
    sheet_names = [name for name in wb.sheetnames if name != "Overview"]
    assert sheet_names, "expected a sheet for the markdown table"
    ws = wb[sheet_names[0]]

    # Numeric cells should be rewritten as real numbers, not strings.
    assert ws.cell(row=2, column=2).value == 1.2
    assert ws.cell(row=2, column=3).value == 0.9

    assert len(ws._charts) == 1


def test_deck_plan_to_markdown_handles_new_layout_hints():
    content = json.dumps({
        "title": "AI Platform Roadmap",
        "slides": [
            {
                "layout": "executive_summary",
                "title": "The platform pays for itself within a year",
                "bullets": ["Cuts run-rate cost by 30%", "Reduces vendor sprawl"],
            },
            {
                "layout": "recommendation",
                "title": "Proceed with consolidation",
                "bullets": ["Consolidate onto Platform A", "Lower long-term TCO"],
            },
            {
                "layout": "roadmap",
                "title": "Three phases",
                "phases": [
                    {"label": "Phase 1", "title": "Foundation", "description": "Stand up infrastructure"},
                ],
            },
            {
                "layout": "appendix",
                "title": "Supporting detail",
                "bullets": ["Extra context"],
            },
        ],
    })

    markdown = deck_plan_to_markdown(content)

    assert markdown is not None
    assert "**Cuts run-rate cost by 30%**" in markdown
    assert "**Recommendation: Consolidate onto Platform A**" in markdown
    assert "Phase 1: Foundation — Stand up infrastructure" in markdown
    assert "# Appendix: Supporting detail" in markdown


def test_deck_plan_to_markdown_returns_readable_slide_plan():
    content = json.dumps({
        "title": "Client AI Strategy",
        "slides": [
            {"layout": "bullets", "title": "The decision is timing-sensitive", "bullets": ["Move in phases"]},
        ],
    })

    markdown = deck_plan_to_markdown(content)

    assert markdown is not None
    assert markdown.startswith("# Client AI Strategy")
    assert "## The decision is timing-sensitive" in markdown
    assert "- Move in phases" in markdown


def test_pptx_layout_for_role_resolves_renamed_layouts_via_heuristic():
    """A template whose layouts have been renamed away from the standard
    PowerPoint names should still resolve to the correct semantic role via
    placeholder-shape heuristics, not just name-matching or index fallback."""
    prs = Presentation()

    p_ns = "{http://schemas.openxmlformats.org/presentationml/2006/main}"

    def _rename(layout, new_name):
        csld = layout.element.find(f"{p_ns}cSld")
        csld.set("name", new_name)

    # Rename "Section Header" (title + body only) away from any keyword match.
    section_layout = prs.slide_layouts[2]
    _rename(section_layout, "Custom Divider Style")

    # Rename "Two Content" and "Comparison" (both title + 2 object placeholders)
    # away from any keyword match.
    two_content_layout = prs.slide_layouts[3]
    _rename(two_content_layout, "Side-by-Side Panels")
    _rename(prs.slide_layouts[4], "Split View")

    resolved_section = _pptx_layout_for_role(prs, "section")
    resolved_two_content = _pptx_layout_for_role(prs, "two_content")

    assert resolved_section is section_layout
    assert resolved_two_content is two_content_layout


def test_pptx_layout_for_role_falls_back_to_index_when_unresolvable():
    """When neither name-matching nor placeholder heuristics find a match,
    resolution should fall back to the standard-index default without error."""
    prs = Presentation()
    layout = _pptx_layout_for_role(prs, "title_only")
    assert layout is prs.slide_layouts[5]

    # Unknown role falls back to index 0 (title slide) gracefully.
    fallback = _pptx_layout_for_role(prs, "nonexistent_role")
    assert fallback is prs.slide_layouts[0]


def _deck_plan_with_crowded_slide() -> dict:
    content = json.dumps({
        "title": "Repair Loop Test",
        "subtitle": "QA repair",
        "slides": [
            {
                "layout": "bullets",
                "title": "Crowded slide",
                "bullets": [f"Bullet number {i} with some supporting detail" for i in range(1, 7)],
            },
            {
                "layout": "timeline",
                "title": "Phased rollout",
                "phases": [
                    {"label": f"Phase {i}", "title": f"Step {i}", "description": f"Detail {i}"}
                    for i in range(1, 5)
                ],
            },
        ],
    })
    return parse_deck_plan(content)


def test_repair_deck_plan_for_qa_drops_last_bullet_on_dense_slide():
    plan = _deck_plan_with_crowded_slide()
    original_bullets = len(plan["slides"][0]["bullets"])

    # Rendered slide 1 is the title slide; slide 2 corresponds to plan["slides"][0].
    issues = [{"slide": 2, "type": "dense_text", "detail": "too much text"}]
    repaired, changed = repair_deck_plan_for_qa(plan, issues)

    assert changed is True
    assert len(repaired["slides"][0]["bullets"]) == original_bullets - 1
    # Unrelated slides are untouched.
    assert repaired["slides"][1] == plan["slides"][1]


def test_repair_deck_plan_for_qa_trims_timeline_phases():
    plan = _deck_plan_with_crowded_slide()
    original_phases = len(plan["slides"][1]["phases"])

    # Rendered slide 3 corresponds to plan["slides"][1].
    issues = [{"slide": 3, "type": "dense_ink", "detail": "visually crowded"}]
    repaired, changed = repair_deck_plan_for_qa(plan, issues)

    assert changed is True
    assert len(repaired["slides"][1]["phases"]) == original_phases - 1


def test_repair_deck_plan_for_qa_no_op_when_nothing_left_to_trim():
    plan = parse_deck_plan(json.dumps({
        "title": "Minimal",
        "slides": [{"layout": "bullets", "title": "Single bullet", "bullets": ["short"]}],
    }))

    issues = [{"slide": 2, "type": "dense_ink", "detail": "visually crowded"}]
    repaired, changed = repair_deck_plan_for_qa(plan, issues)

    assert changed is False
    assert repaired == plan


def test_repair_deck_plan_for_qa_ignores_non_density_issues():
    plan = _deck_plan_with_crowded_slide()
    issues = [{"slide": 1, "type": "blank", "detail": "title slide appears blank"}]
    repaired, changed = repair_deck_plan_for_qa(plan, issues)

    assert changed is False
    assert repaired == plan


def test_parse_deck_plan_assigns_slide_blueprint_fields():
    plan = parse_deck_plan(json.dumps({
        "title": "Roadmap",
        "slides": [
            {"layout": "bullets", "title": "Short slide", "bullets": ["One point"]},
            {
                "layout": "timeline",
                "title": "Phased rollout",
                "phases": [
                    {"label": "Phase 1", "title": "Foundation", "description": "Set up"},
                    {"label": "Phase 2", "title": "Migration", "description": "Move"},
                    {"label": "Phase 3", "title": "Optimization", "description": "Tune"},
                ],
            },
            {
                "layout": "financial_model",
                "title": "Cost outlook",
                "chart": {
                    "type": "bar",
                    "categories": ["2025", "2026"],
                    "series": [{"name": "Cost", "values": [1, 2]}],
                },
            },
        ],
    }))

    assert plan is not None
    low_slide, timeline_slide, chart_slide = plan["slides"]

    # Low-content bullets slide: low density, no visual object.
    assert low_slide["archetype"] == "bullets"
    assert low_slide["density"] == "low"
    assert low_slide["visual_object"] is None

    # Timeline with 3 phases: visual_object is "timeline".
    assert timeline_slide["archetype"] == "timeline"
    assert timeline_slide["visual_object"] == "timeline"

    # Chart-bearing slide: visual_object is "chart".
    assert chart_slide["archetype"] == "financial_model"
    assert chart_slide["visual_object"] == "chart"


def test_parse_deck_plan_explicit_density_and_archetype_are_respected():
    plan = parse_deck_plan(json.dumps({
        "title": "Roadmap",
        "slides": [
            {
                "layout": "bullets",
                "archetype": "proof_point",
                "density": "high",
                "title": "One big idea",
                "bullets": ["Single bullet"],
            },
        ],
    }))

    assert plan is not None
    slide = plan["slides"][0]
    assert slide["archetype"] == "proof_point"
    assert slide["density"] == "high"


def test_parse_deck_plan_routes_overflow_bullets_and_long_text_to_speaker_notes():
    long_bullet = "This bullet is intentionally far too long to fit on a single slide line " * 2
    plan = parse_deck_plan(json.dumps({
        "title": "Roadmap",
        "slides": [
            {
                "layout": "bullets",
                "title": "Crowded slide",
                "bullets": [
                    long_bullet,
                    "Bullet two", "Bullet three", "Bullet four",
                    "Bullet five", "Bullet six", "Bullet seven",
                ],
                "speaker_notes": "Existing talk track.",
            },
        ],
    }))

    assert plan is not None
    slide = plan["slides"][0]

    # Only the first MAX_BULLETS_PER_SLIDE (6) bullets are kept visible.
    assert len(slide["bullets"]) == 6
    assert all(len(b) <= 90 for b in slide["bullets"])

    # The dropped 7th bullet and the truncated long bullet's full text both
    # land in speaker_notes alongside the original notes.
    assert "Existing talk track." in slide["speaker_notes"]
    assert "Bullet seven" in slide["speaker_notes"]
    assert "intentionally far too long" in slide["speaker_notes"]


def test_repair_deck_plan_for_qa_preserves_dropped_bullet_in_speaker_notes():
    plan = _deck_plan_with_crowded_slide()
    issues = [{"slide": 2, "type": "dense_text", "detail": "too much text"}]
    repaired, changed = repair_deck_plan_for_qa(plan, issues)

    assert changed is True
    slide = repaired["slides"][0]
    assert len(slide["bullets"]) == 5
    assert any("Trimmed for slide density" in n for n in slide["speaker_notes"].splitlines())
    assert slide["density"] in {"low", "medium", "high"}
