from io import BytesIO

from docx import Document

from app.services.document_generator import generate_docx_bytes


def _read_docx(content: bytes) -> Document:
    return Document(BytesIO(content))


def test_generate_docx_renders_headings_lists_and_text():
    content = """# Recommendation

Use the low-overhead option.

## Next steps
- Configure the database
- Run migrations
1. Smoke test production
2. Watch costs
"""
    doc = _read_docx(generate_docx_bytes("Deployment plan", content, "Generated by Fronei"))

    text = "\n".join(p.text for p in doc.paragraphs)
    assert "Deployment plan" in text
    assert "Generated by Fronei" in text
    assert "Recommendation" in text
    assert "Use the low-overhead option." in text
    assert "Configure the database" in text
    assert "Smoke test production" in text


def test_generate_docx_renders_markdown_table():
    content = """| Option | Cost | Notes |
| --- | --- | --- |
| Railway | Low | Lowest overhead |
| VPS | Lower | More maintenance |
"""
    doc = _read_docx(generate_docx_bytes("Hosting comparison", content))

    assert len(doc.tables) == 1
    table = doc.tables[0]
    assert table.cell(0, 0).text == "Option"
    assert table.cell(1, 0).text == "Railway"
    assert table.cell(2, 2).text == "More maintenance"
