"""add auth - users table and user_id columns

Revision ID: ad98597a4589
Revises: f8372fd84be2
Create Date: 2026-06-08 16:21:04.441232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.db.migration_helpers import column_exists, index_exists, table_exists


# revision identifiers, used by Alembic.
revision: str = 'ad98597a4589'
down_revision: Union[str, Sequence[str], None] = 'f8372fd84be2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    if not table_exists('users'):
        op.create_table(
            'users',
            sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
            sa.Column('clerk_id', sa.String(length=128), nullable=False),
            sa.Column('email', sa.String(length=255), nullable=True),
            sa.Column('name', sa.String(length=120), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=False),
            sa.Column('last_login_at', sa.DateTime(), nullable=True),
            sa.PrimaryKeyConstraint('id'),
            if_not_exists=True,
        )
    if not index_exists('users', 'ix_users_clerk_id'):
        op.create_index('ix_users_clerk_id', 'users', ['clerk_id'], unique=True)

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        if not column_exists('conversations', 'user_id'):
            batch_op.add_column(sa.Column('user_id', sa.String(length=128), nullable=False, server_default=''))
        if not index_exists('conversations', batch_op.f('ix_conversations_user_id')):
            batch_op.create_index(batch_op.f('ix_conversations_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('request_logs', schema=None) as batch_op:
        if not column_exists('request_logs', 'user_id'):
            batch_op.add_column(sa.Column('user_id', sa.String(length=128), nullable=False, server_default=''))
        if not index_exists('request_logs', batch_op.f('ix_request_logs_user_id')):
            batch_op.create_index(batch_op.f('ix_request_logs_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_request_logs_user_id'))
        batch_op.drop_column('user_id')

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversations_user_id'))
        batch_op.drop_column('user_id')

    op.drop_index('ix_users_clerk_id', table_name='users')
    op.drop_table('users')

    # ### end Alembic commands ###
